### ISSUE TITLE
Dev Cycle integration to Jira

### ISSUE THREAD

**Issue by kjscholl** [DevCycleHQ/.github#4]
Hi, 

I recently added the Dev Cycle integration with Jira. In the implementation guide, it says there should be a space to add the Dev Cycle token into jira but I am not seeing that UI option in Jira. I also chatted with a Jira support team member and they do not see that option as well. Is there another way to connect our Jira account to Dev Cycle?
https://docs.devcycle.com/integrations/Jira/jira-integration - step 3

**Comment by L-Joli** [comment]
Hi @kjscholl, thank you for reaching out! Would it be possible for you to provide a screenshot of the DevCycle Jira configuration page? This would greatly assist us in investigating the issue.

**Comment by kjscholl** [comment]
@L-Joli here you go!
<img width="1436" alt="image" src="https://github.com/DevCycleHQ/.github/assets/116685078/d764c8be-0956-4d2e-8521-0d6cdd0bec5a">

**Comment by L-Joli** [comment]
@kjscholl thanks! Sorry for asking again, are you getting this page by clicking Apps > DevCycle?
![devcycle-jira](https://github.com/DevCycleHQ/.github/assets/69351113/b5bc0b9c-b60c-4698-970d-4000f72846ea)

**Comment by kjscholl** [comment]
@L-Joli Oooooo! I totally missed that option up there. I was able to add the token and it is working now - thank you!!

**Comment by L-Joli** [comment]
@kjscholl great to hear that!
